In [1]:
print("Hello Jupyter")

Hello Jupyter

In [2]:
import pandas as pd

df = pd.read_csv("customer_shopping_behaviour.csv")   # CSV file
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behaviour.csv'

In [3]:
import os
os.listdir()

['.bash_history',
 '.EasyOCR',
 '.git',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.node_repl_history',
 '.vscode',
 '.vscode-shared',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'customer_shopping_behaviour.csv.xlsx',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.0.regtrans-ms',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.1.regtrans-ms',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.2.regtrans-ms',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.blf',
 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TM.blf',
 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'Videos']

In [4]:
import pandas as pd

df = pd.read_excel("customer_shopping_behaviour.csv.xlsx")
df.head()

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             20 non-null     int64
 1   Age                     20 non-null     int64
 2   Gender                  20 non-null     str
 3   Item purchage           20 non-null     str
 4   Category                20 non-null     str
 5   Puchrase amount         20 non-null     int64
 6   Location                20 non-null     str
 7   Size                    20 non-null     str
 8   Colour                  20 non-null     str
 9   Season                  20 non-null     str
 10  Review Rate             20 non-null     float64
 11  Subscription Status     20 non-null     str
 12  Shpping type            20 non-null     str
 13  Discount applied        20 non-null     str
 14  Prmomocode Used         20 non-null     str
 15  Previous purchages      20 non-null     int64
 16  Payment Method          20 non-null     str
 17  Frequency of Purchases  20 non-null     str
dtypes: float64(1), int64(4), str(13)
memory usage: 2.9 KB

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
count,20.00000,20.000000,20,20,20,20.0000,20,20,20,20,20.000000,20,20,20,20,20.000000,20,20
unique,NaN,NaN,2,13,4,NaN,17,4,15,4,NaN,1,6,1,1,NaN,6,6
top,NaN,NaN,Male,coat,Clothing,NaN,Rhode Isla,M,Gray,Winter,NaN,Yes,Free Shipping,Yes,Yes,NaN,Venmo,Weekly
freq,NaN,NaN,19,3,12,NaN,3,9,3,8,NaN,20,6,20,20,NaN,5,8
mean,10.50000,47.100000,NaN,NaN,NaN,58.3500,NaN,NaN,NaN,NaN,3.730000,NaN,NaN,NaN,NaN,25.100000,NaN,NaN
std,5.91608,16.325311,NaN,NaN,NaN,22.7926,NaN,NaN,NaN,NaN,0.822128,NaN,NaN,NaN,NaN,15.375647,NaN,NaN
min,1.00000,19.000000,NaN,NaN,NaN,20.0000,NaN,NaN,NaN,NaN,2.600000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN
25%,5.75000,29.250000,NaN,NaN,NaN,37.5000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,10.50000,52.500000,NaN,NaN,NaN,53.0000,NaN,NaN,NaN,NaN,3.400000,NaN,NaN,NaN,NaN,24.500000,NaN,NaN
75%,15.25000,61.500000,NaN,NaN,NaN,75.0000,NaN,NaN,NaN,NaN,4.625000,NaN,NaN,NaN,NaN,36.250000,NaN,NaN
max,20.00000,66.000000,NaN,NaN,NaN,97.0000,NaN,NaN,NaN,NaN,4.900000,NaN,NaN,NaN,NaN,49.000000,NaN,NaN

In [8]:
df.isnull.().sum()

SyntaxError: invalid syntax (1874293021.py, line 1)

In [9]:
df.isnumull().sum()

AttributeError: 'DataFrame' object has no attribute 'isnumull'

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item purchage             0
Category                  0
Puchrase amount           0
Location                  0
Size                      0
Colour                    0
Season                    0
Review Rate               0
Subscription Status       0
Shpping type              0
Discount applied          0
Prmomocode Used           0
Previous purchages        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df['Review rate']=df.groupby('Category')'['Review Rate'].transform(lamba x: x.filna(x.medium())

SyntaxError: unterminated string literal (detected at line 1) (3782249883.py, line 1)

In [12]:
df['Review Rate'] = df.groupby('Category')['Review Rate'].transform(lambda x: x.fillna(x.median()))

In [13]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item purchage             0
Category                  0
Puchrase amount           0
Location                  0
Size                      0
Colour                    0
Season                    0
Review Rate               0
Subscription Status       0
Shpping type              0
Discount applied          0
Prmomocode Used           0
Previous purchages        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [19]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df=df.rename(columns={puchrase_amount':'puchrase_amount'})

SyntaxError: unterminated string literal (detected at line 3) (1242391177.py, line 3)

In [20]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchage', 'category',
       'puchrase_amount', 'location', 'size', 'colour', 'season',
       'review_rate', 'subscription_status', 'shpping_type',
       'discount_applied', 'prmomocode_used', 'previous_purchages',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchage', 'category',
       'puchrase_amount', 'location', 'size', 'colour', 'season',
       'review_rate', 'subscription_status', 'shpping_type',
       'discount_applied', 'prmomocode_used', 'previous_purchages',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [22]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchage', 'category',
       'puchrase_amount', 'location', 'size', 'colour', 'season',
       'review_rate', 'subscription_status', 'shpping_type',
       'discount_applied', 'prmomocode_used', 'previous_purchages',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [23]:
df['puchrase_amount']

0     53
1     64
2     73
3     90
4     49
5     20
6     85
7     34
8     97
9     31
10    34
11    68
12    72
13    51
14    53
15    81
16    36
17    38
18    48
19    90
Name: puchrase_amount, dtype: int64

In [24]:
df.rename(columns={'puchrase_amount': 'purchase_amount'}, inplace=True)

In [25]:
df['purchase_amount']

0     53
1     64
2     73
3     90
4     49
5     20
6     85
7     34
8     97
9     31
10    34
11    68
12    72
13    51
14    53
15    81
16    36
17    38
18    48
19    90
Name: purchase_amount, dtype: int64

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchage', 'category',
       'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rate', 'subscription_status', 'shpping_type',
       'discount_applied', 'prmomocode_used', 'previous_purchages',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [27]:
#create a column age_group
labels=['Young Adult','Adult','Middle-Age','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [28]:
df[['age','age_group']].head(10)

   age    age_group
0   55   Middle-Age
1   19  Young Adult
2   50        Adult
3   21  Young Adult
4   45        Adult
5   46        Adult
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57   Middle-Age

In [36]:
#create column purchase_frequency_days

frequency_mapping = {
    'Daily': 1,
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Annually': 365
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [37]:
df[['frequency_of_purchases']].head(10)

  frequency_of_purchases
0            Fortnightly
1            Fortnightly
2                 Weekly
3                 Weekly
4               Annually
5                 Weekly
6              Quarterly
7                 Weekly
8               Annually
9              Quarterly

In [38]:
frequency_mapping = {
    'Daily': 1,
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Annually': 365
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [39]:
df[['frequency_of_purchases','purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                      NaN
1            Fortnightly                      NaN
2                 Weekly                      7.0
3                 Weekly                      7.0
4               Annually                    365.0
5                 Weekly                      7.0
6              Quarterly                     90.0
7                 Weekly                      7.0
8               Annually                    365.0
9              Quarterly                     90.0

In [42]:
df[['discount_applied','prmomocode_used']].head(10)

  discount_applied prmomocode_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [45]:
(df['discount_applied'] == df['prmomocode_used']).all()

np.True_

In [47]:
df = df.drop('prmomocode_used', axis=1)

In [48]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchage', 'category',
       'purchase_amount', 'location', 'size', 'colour', 'season',
       'review_rate', 'subscription_status', 'shpping_type',
       'discount_applied', 'previous_purchages', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [51]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in .\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import psycopg2
import sqlalchemy

print("All good ✅")

All good ✅

In [5]:
# Step 1: Connect to PostgreSQL

from sqlalchemy import create_engine

# Replace with your details
username = "postgres"          # default user
password = "anishka"          # your PostgreSQL password
host = "localhost"             # running locally
port = "5432"                  # default port
database = "customer_behaviour" # your database name

# Create connection
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


# Step 2: Load DataFrame into PostgreSQL

table_name = "customer"   # table name

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}' ✅")

Data successfully loaded into table 'customer' in database 'customer_behaviour' ✅

In [7]:
pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

Empty DataFrame
Columns: [name, age]
Index: []

In [9]:
import pandas as pd

pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

Empty DataFrame
Columns: [name, age]
Index: []

In [11]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS customer"))
    conn.commit()

print("Table deleted successfully")

Table deleted successfully

In [12]:
df.to_sql("customer", engine, if_exists="replace", index=False)

print("Data loaded successfully")

Data loaded successfully

In [13]:
import pandas as pd

pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

      name  age
0  Anishka   20
1    Rahul   22
2    Priya   21

In [14]:
print(df.shape)
print(df.columns)

(3, 2)
Index(['name', 'age'], dtype='str')

In [15]:
pd.read_sql("SELECT current_database();", engine)

     current_database
0  customer_behaviour

In [16]:
pd.read_sql("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
""", engine)

  table_name
0   customer

In [17]:
pd.read_sql("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';
""", engine)

  column_name
0         age
1        name

In [18]:
df.to_sql("customer_new", engine, if_exists="replace", index=False)

3

In [19]:
pd.read_sql("""
SELECT column_name
FROM information_schema.columns
WHERE table_name='customer_new';
""", engine)

  column_name
0         age
1        name

In [20]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS customer"))
    conn.commit()

In [21]:
df.to_sql("customer", engine, if_exists="replace", index=False)

3

In [22]:
import pandas as pd

df = pd.read_excel("customer_shopping_behaviour.csv.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behaviour.csv.xlsx'

In [23]:
import os

print(os.listdir())

['.bash_history', '.EasyOCR', '.git', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.node_repl_history', '.vscode', '.vscode-shared', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'customer_shopping_behaviour_analysis.ipynb', 'Desktop', 'Documents', 'Downloads', 'Favorites', 'IntelGraphicsProfiles', 'Links', 'Local Settings', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.0.regtrans-ms', 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.1.regtrans-ms', 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.2.regtrans-ms', 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.blf', 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TM.blf', 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled Folder', 'Videos']

In [24]:
import os
print(os.getcwd())

C:\Users\WELCOME

In [25]:
import os

for root, dirs, files in os.walk("Downloads"):
    for file in files:
        if "customer" in file.lower():
            print(os.path.join(root, file))

In [26]:
for root, dirs, files in os.walk("Desktop"):
    for file in files:
        if "customer" in file.lower():
            print(os.path.join(root, file))

Desktop\customer_shopping_behaviour.csv
Desktop\customer_shopping_behaviour.csv.xlsx
Desktop\expense-tracker\expense-tracker\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\expense-tracker\expense-tracker\node_modules\csso\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\expense-tracker\expense-tracker\node_modules\postcss-svgo\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\frontend\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\frontend\node_modules\csso\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\frontend\node_modules\postcss-svgo\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\node_modules\csso\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\node_modules\postcss-svgo\node_modules\css-tree\lib\utils\createCustomError.js

In [27]:
import pandas as pd

df = pd.read_csv("customer_shopping_behaviour.csv")   # CSV file
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behaviour.csv'

In [28]:
import os
os.listdir()

['.bash_history',
 '.EasyOCR',
 '.git',
 '.gitconfig',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.node_repl_history',
 '.vscode',
 '.vscode-shared',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'customer_shopping_behaviour_analysis.ipynb',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Links',
 'Local Settings',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.0.regtrans-ms',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.1.regtrans-ms',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.2.regtrans-ms',
 'NTUSER.DAT{3f18ceed-494d-11f1-b1ce-ac74b1ca1787}.TxR.blf',
 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TM.blf',
 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{3f18ceee-494d-11f1-b1ce-ac74b1ca1787}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled Folder',
 'Videos']

In [29]:
import pandas as pd

df = pd.read_excel("customer_shopping_behaviour.csv.xlsx")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'customer_shopping_behaviour.csv.xlsx'

In [30]:
import os
print(os.getcwd())

C:\Users\WELCOME

In [31]:
import os

for root, dirs, files in os.walk("Downloads"):
    for file in files:
        if "customer" in file.lower():
            print(os.path.join(root, file))

In [32]:
for root, dirs, files in os.walk("Desktop"):
    for file in files:
        if "customer" in file.lower():
            print(os.path.join(root, file))

Desktop\customer_shopping_behaviour.csv
Desktop\customer_shopping_behaviour.csv.xlsx
Desktop\expense-tracker\expense-tracker\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\expense-tracker\expense-tracker\node_modules\csso\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\expense-tracker\expense-tracker\node_modules\postcss-svgo\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\frontend\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\frontend\node_modules\csso\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\frontend\node_modules\postcss-svgo\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\node_modules\csso\node_modules\css-tree\lib\utils\createCustomError.js
Desktop\zerodha project app anishka\frontend\node_modules\postcss-svgo\node_modules\css-tree\lib\utils\createCustomError.js

In [33]:
df = pd.read_csv(r"Desktop\customer_shopping_behaviour.csv")
df.head()

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [34]:
df = pd.read_csv(r"Desktop\customer_shopping_behaviour.csv")

In [35]:
df.head()

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [36]:
pd.read_sql("SELECT current_database();", engine)

     current_database
0  customer_behaviour

In [37]:
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

      name  age
0  Anishka   20
1    Rahul   22
2    Priya   21

In [38]:
df = pd.read_csv(r"Desktop\customer_shopping_behaviour.csv")

df.head()

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [39]:
print(df.columns)

Index(['Customer ID', 'Age', 'Gender', 'Item purchage', 'Category',
       'Puchrase amount', 'Location', 'Size', 'Colour', 'Season',
       'Review Rate', 'Subscription Status', 'Shpping type',
       'Discount applied', 'Prmomocode Used', 'Previous purchages',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [40]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS customer"))
    conn.commit()

In [41]:
df.to_sql("customer", engine, if_exists="replace", index=False)

20

In [42]:
pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [43]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS customer"))
    conn.commit()

print("Old table deleted")

Old table deleted

In [44]:
df.to_sql("customer", engine, if_exists="replace", index=False)

print("Shopping data uploaded")

Shopping data uploaded

In [45]:
pd.read_sql("SELECT * FROM customer LIMIT 5", engine)

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [46]:
pip install pyodbc sqlalachemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement sqlalachemy (from versions: none)
ERROR: No matching distribution found for sqlalachemy

In [48]:
pip install pyodbc sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Collecting pyodbc
  Using cached pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pyodbc
import sqlalchemy

print("Libraries Installed Successfully")

Libraries Installed Successfully

In [2]:
from sqlalchemy import create_engine

server = "localhost"
database = "customer_behaviour"

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

print("Connected Successfully")

Connected Successfully

In [4]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [5]:
pip install pyodbc sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in .\AppData\Roaming\Python\Python314\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
import os
print(os.path.expanduser("~"))

C:\Users\WELCOME

In [9]:
df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

In [10]:
import pandas as pd

df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

print(df.head())

   Customer ID  Age Gender Item purchage  Category  Puchrase amount  \
0            1   55   Male        blouse  Clothing               53
1            2   19   Male       sweater  Clothing               64
2            3   50   Male         jeans  Clothing               73
3            4   21   Male        sandal  Footwear               90
4            5   45   Male        blouse  Clothing               49

     Location Size    Colour  Season  Review Rate Subscription Status  \
0    Kenlucky    L      Gray  Winter          3.1                 Yes
1       Maine    L    Maroon  Winter          3.1                 Yes
2    Massachu    S    Maroon  Spring          3.1                 Yes
3  Rhode Isla    M    Maroon  Spring          3.5                 Yes
4      Oregon    M  Turqoise  Spring          2.7                 Yes

    Shpping type Discount applied Prmomocode Used  Previous purchages  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3       Next Day              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# CSV already loaded (tumne bola aa gaya)
df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

# MySQL connection
username = "root"
password = "anishka"
host = "localhost"
port = "3306"
database = "mydatabase"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Table name
table_name = "mytable"

# Upload to MySQL
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Verify
result = pd.read_sql("SELECT * FROM mytable LIMIT 5", engine)
print(result)

In [12]:
pip install pyodbc sqlalchemy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in .\AppData\Roaming\Python\Python314\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python314\site-packages (3.0.3)
Requirement already satisfied: greenlet>=1 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Load CSV
df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

# MS SQL Server (Windows Authentication)
server = "localhost"
database = "mydatabase"

engine = create_engine(
    "mssql+pyodbc://@localhost/mydatabase?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

# Table name
table_name = "mytable"

# Upload data
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Verify
result = pd.read_sql(f"SELECT TOP 5 * FROM {table_name}", engine)
print(result)

InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [1]:
print("Jupyter working")

Jupyter working

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")
df.head()

,Customer ID,Age,Gender,Item purchage,Category,Puchrase amount,Location,Size,Colour,Season,Review Rate,Subscription Status,Shpping type,Discount applied,Prmomocode Used,Previous purchages,Payment Method,Frequency of Purchases
0,1,55,Male,blouse,Clothing,53,Kenlucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,jeans,Clothing,73,Massachu,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit card,Weekly
3,4,21,Male,sandal,Footwear,90,Rhode Isla,M,Maroon,Spring,3.5,Yes,Next Day,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,blouse,Clothing,49,Oregon,M,Turqoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [6]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)', 'ODBC Driver 18 for SQL Server']

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

engine = create_engine(
    "mssql+pyodbc://@localhost/mydatabase?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&Encrypt=no"
)

df.to_sql("mytable", engine, if_exists="replace", index=False)

print("DATA UPLOADED SUCCESSFULLY")

In [1]:
print("hello")

hello

In [1]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

engine = create_engine(
    "mssql+pyodbc://DESKTOP-O3UFEPG\\SQLEXPRESS/mydatabase"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&trusted_connection=yes"
    "&Encrypt=no"
)

df.to_sql("mytable", engine, if_exists="replace", index=False)

print("DATA UPLOADED SUCCESSFULLY")

InterfaceError: (pyodbc.InterfaceError) ('28000', '[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user \'DESKTOP-O3UFEPG\\WELCOME\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "mydatabase" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user \'DESKTOP-O3UFEPG\\WELCOME\'. (18456); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "mydatabase" requested by the login. The login failed. (4060)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [2]:
CREATE DATABASE mydatabase;

SyntaxError: invalid syntax (3144249553.py, line 1)

In [4]:
"DESKTOP-O3UFEPG\\SQLEXPRESS"

'DESKTOP-O3UFEPG\\SQLEXPRESS'

In [5]:
from sqlalchemy import create_engine
import pandas as pd

df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

engine = create_engine(
    "mssql+pyodbc://DESKTOP-O3UFEPG\\SQLEXPRESS/mydatabase"
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&trusted_connection=yes"
    "&Encrypt=no"
)

df.to_sql("mytable", engine, if_exists="replace", index=False)

print("DATA UPLOADED SUCCESSFULLY")

InterfaceError: (pyodbc.InterfaceError) ('28000', '[28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user \'DESKTOP-O3UFEPG\\WELCOME\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "mydatabase" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Login failed for user \'DESKTOP-O3UFEPG\\WELCOME\'. (18456); [28000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Cannot open database "mydatabase" requested by the login. The login failed. (4060)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [7]:
from sqlalchemy import create_engine
import pandas as pd

df = pd.read_csv(r"C:\Users\WELCOME\Desktop\customer_shopping_behaviour.csv")

engine = create_engine(
    "mssql+pyodbc://DESKTOP-O3UFEPG\\SQLEXPRESS/mydatabase?driver=ODBC+Driver+18+for+SQL+Server&trusted_connection=yes&Encrypt=no"
)

df.to_sql("mytable", engine, if_exists="replace", index=False)

print("DATA UPLOADED SUCCESSFULLY")

DATA UPLOADED SUCCESSFULLY